#!/bin/bash
set -euo pipefail

# ─── WorldLens Deployment Script ───────────────────────────────────────
# This script provisions all AWS infrastructure and prepares the app.
# Prerequisites: AWS CLI configured with appropriate credentials.
#
# Usage: ./scripts/deploy.sh
# ───────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$PROJECT_DIR/infrastructure"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  WorldLens — Automated Deployment"
echo "════════════════════════════════════════════════════════════"
echo ""

# ─── Step 1: Verify Prerequisites ──────────────────────────────────────

echo "🔍 Checking prerequisites..."

if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Install from https://aws.amazon.com/cli/"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo "❌ Node.js not found."
    exit 1
fi

echo "   ✓ AWS CLI found: $(aws --version 2>&1 | head -1)"
echo "   ✓ Node.js found: $(node --version)"

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run 'aws configure' first."
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
echo "   ✓ AWS Account: $ACCOUNT_ID"
echo "   ✓ AWS Region: $REGION"
echo ""

# ─── Step 2: Deploy CDK Infrastructure ─────────────────────────────────

echo "🏗️  Step 1/3: Deploying CDK infrastructure..."
cd "$INFRA_DIR"

if [ ! -d "node_modules" ]; then
    echo "   📦 Installing CDK dependencies..."
    npm install --silent
fi

# Ensure esbuild is installed locally for Docker-less bundling
if ! npm list esbuild --depth=0 &> /dev/null; then
    echo "   📦 Installing esbuild for local bundling..."
    npm install --save-dev esbuild@0.21.5 --silent
fi

echo "   ☁️  Bootstrapping CDK..."
npx cdk bootstrap "aws://$ACCOUNT_ID/$REGION" --quiet 2>/dev/null || true

echo "   🚀 Deploying stack..."
npx cdk deploy --require-approval never --outputs-file cdk-outputs.json

echo "   ✓ CDK infrastructure deployed!"
echo ""

# ─── Step 3: Extract Outputs & Configure .env ──────────────────────────

echo "⚙️  Step 2/3: Configuring environment..."

WS_URL=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.WebSocketUrl || '')")
SESSIONS_TABLE=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.SessionsTableName || 'WorldLensSessions')")
IDENTITY_POOL_ID=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.CognitoIdentityPoolId || '')")
BEDROCK_REGION=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.BedrockRegion || '')")
SONIC_PROFILE_ARN=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensBedrockProfiles?.SonicInferenceProfileArn || '')")
LITE_PROFILE_ARN=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensBedrockProfiles?.LiteInferenceProfileArn || '')")
ACCESS_KEY_ID=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.DevUserAccessKeyId || '')")
SECRET_ACCESS_KEY=$(node -e "const o = require('./cdk-outputs.json'); console.log(o.WorldLensStack?.DevUserSecretAccessKey || '')")

if [ -z "$WS_URL" ]; then
    echo "⚠️  Warning: WebSocket URL not found in CDK outputs"
else
    echo "   ✓ WebSocket URL: $WS_URL"
fi

if [ -z "$ACCESS_KEY_ID" ]; then
    echo "⚠️  Warning: Local dev credentials not found in CDK outputs"
else
    echo "   ✓ IAM Credentials generated"
fi

# Cognito / Bedrock outputs
if [ -z "$IDENTITY_POOL_ID" ]; then
    echo "⚠️  Warning: Cognito Identity Pool ID not found in CDK outputs"
else
    echo "   ✓ Cognito Identity Pool ID: $IDENTITY_POOL_ID"
fi

if [ -z "$BEDROCK_REGION" ]; then
    echo "⚠️  Warning: Bedrock region not found in CDK outputs"
else
    echo "   ✓ Bedrock region: $BEDROCK_REGION"
fi

if [ -z "$SONIC_PROFILE_ARN" ]; then
    echo "⚠️  Warning: Sonic inference profile ARN not found in CDK outputs"
else
    echo "   ✓ Sonic inference profile ARN: $SONIC_PROFILE_ARN"
fi

if [ -z "$LITE_PROFILE_ARN" ]; then
    echo "⚠️  Warning: Lite inference profile ARN not found in CDK outputs"
else
    echo "   ✓ Lite inference profile ARN: $LITE_PROFILE_ARN"
fi

# Write .env.local for Next.js
cat > "$PROJECT_DIR/.env.local" << EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AWS_REGION=$REGION
AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
NEXT_PUBLIC_AWS_REGION=$REGION
NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
NEXT_PUBLIC_BEDROCK_REGION=$BEDROCK_REGION
NEXT_PUBLIC_SONIC_INFERENCE_PROFILE_ARN=$SONIC_PROFILE_ARN
NOVA_LITE_INFERENCE_PROFILE_ARN=$LITE_PROFILE_ARN
SESSIONS_TABLE=$SESSIONS_TABLE
EOF

echo "   ✓ .env.local written"
echo ""

# ─── Step 4: Build Next.js ──────────────────────────────────────────────

echo "🔨 Step 3/3: Building Next.js application..."
cd "$PROJECT_DIR"

if [ ! -d "node_modules" ]; then
    echo "   📦 Installing app dependencies..."
    npm ci --silent
fi

npm run build

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ Deployment Complete!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  WebSocket URL: $WS_URL"
echo "  Sessions Table: $SESSIONS_TABLE"
echo "  Cognito Identity Pool ID: $IDENTITY_POOL_ID"
echo "  Bedrock region: $BEDROCK_REGION"
echo "  Sonic inference profile ARN: $SONIC_PROFILE_ARN"
echo "  Lite inference profile ARN: $LITE_PROFILE_ARN"
echo ""
echo "  To run locally:  npm run dev"
echo "  To deploy to Amplify: git push (if Amplify is connected)"
echo ""
